// <auto-generated />
namespace Course.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration_rate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_rate));
        
        string IMigrationMetadata.Id
        {
            get { return "201611091039301_migration_rate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
