// <auto-generated />
namespace Course.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class badge_url : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(badge_url));
        
        string IMigrationMetadata.Id
        {
            get { return "201611171837092_badge_url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
