// <auto-generated />
namespace Course.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cascade_delete_ratings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascade_delete_ratings));
        
        string IMigrationMetadata.Id
        {
            get { return "201611151806491_cascade_delete_ratings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
