// <auto-generated />
namespace Course.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class header_order_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(header_order_column));
        
        string IMigrationMetadata.Id
        {
            get { return "201611171237249_header_order_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
